---
- name: Create "{{ nwapp_kit }}" directory
  file:
    path: "{{ nwapp_kit }}"
    state: directory
    mode: 0777

- name: Create "{{ nwapp_kit }}"/swpm directory
  file:
    path: "{{ nwapp_kit }}/swpm"
    state: directory
    mode: 0777

- name: Create "{{ nwapp_kit }}"/hdbclient directory
  file:
    path: "{{ nwapp_kit }}/hdbclient"
    state: directory
    mode: 0777

- name: Copy "{{ kit_sapcar_file }}" kit to target
  copy:
    src: "{{ kit_sapcar_file }}"
    dest: "{{ nwapp_kit }}/sapcar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_swpm_file }}" kit to target
  copy:
    src: "{{ kit_swpm_file }}"
    dest: "{{ nwapp_kit }}/swpm.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_saphotagent_file }}" kit to target
  copy:
    src: "{{ kit_saphotagent_file }}"
    dest: "{{ nwapp_kit }}/saphotagent.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_hdbclient_file }}" kit to target
  copy:
    src: "{{ kit_hdbclient_file }}"
    dest: "{{ nwapp_kit }}/hdbclient.sar"
    owner: root
    group: root
    mode: 0777

- name: Extract HDBClient archive
  command: "{{ nwapp_kit }}/sapcar -xf {{ nwapp_kit }}/hdbclient.sar -R {{ nwapp_kit }}/hdbclient"

- name: Extract SWPM archive
  command: "{{ nwapp_kit }}/sapcar -xf {{ nwapp_kit }}/swpm.sar -R {{ nwapp_kit }}/swpm"

...
